//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osat
{
    using System;
    using System.Collections.Generic;
    
    public partial class dpw_osat_Employees
    {
        public int ID { get; set; }
        public string DEPTID { get; set; }
        public string C_Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Init { get; set; }
        public string Name_Suffix { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Emp_Date { get; set; }
        public string Title { get; set; }
        public string Division { get; set; }
        public string Section { get; set; }
        public string Class_Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Create_User { get; set; }
        public string Last_Updated_User { get; set; }
        public string Comments { get; set; }
        public string Ethnic_Group { get; set; }
        public Nullable<System.DateTime> RehireDate { get; set; }
    }
}
