//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPW_OBC_PrequalEntities : DbContext
    {
        public DPW_OBC_PrequalEntities()
            : base("name=DPW_OBC_PrequalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dpw_osat_Course> dpw_osat_Course { get; set; }
        public virtual DbSet<dpw_osat_Employees> dpw_osat_Employees { get; set; }
        public virtual DbSet<dpw_osat_Training> dpw_osat_Training { get; set; }
    }
}
